---
title: "Getting and Cleaning Data Project"
author: "VC2015"
date: "July 24, 2015"
output:
  html_document:
    keep_md: yes
---

## Summary

This is a rep for the course project. This repo explains how all of the scripts work and how they are connected. 

## Background 

This repo explains how all of the scripts work and how they are connected. One of the most exciting areas in all of data science right now is wearable computing - see for example this article.  Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

The data for the project:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

##  Scripts and the Code Book:

The R script called run_analysis.R that does the following:

- 1) Merges the training and the test sets to create one data set.
- 2) Extracts only the measurements on the mean and standard deviation for each measurement. 
- 3) Uses descriptive activity names to name the activities in the data set
- 4) Appropriately labels the data set with descriptive variable names. 
- 5) Creates a second, independent tidy data set with the average of each variable for each activity and each subject. 


The Codebook.md describes the variables, the data, and any transformations or work that was performed 
by the run_analysis.R.




 